FROM node:16.10
RUN npm install -g pnpm

WORKDIR /usr/src/app
COPY package*.json nx.json ./
COPY apps/website/package.json ./apps/website/package.json


RUN pnpm install

COPY apps/website ./apps/website

RUN pnpm install

EXPOSE 3000
RUN pnpm nx run website:build
CMD [ "pnpm", "start:website" ]
