version: '2'
services:
  website:
    build: 
      context: .
      dockerfile: apps/website/Dockerfile
    ports:
      - "3000:3000"
    
  editor:
    build: 
      context: .
      dockerfile: apps/editor/Dockerfile
    ports:
      - "80:80"    


