version: '2'
services:
  website:
    build: 
      context: .
      dockerfile: Dockerfile.website
    labels:
      - 'traefik.http.routers.prompto.rule=Host(`promp.to`)'
      - 'traefik.http.routers.prompto.tls.certresolver=le'
      - 'traefik.http.routers.prompto.entrypoints=websecure'
      - 'traefik.docker.network=traefik-external'
    networks:
      - traefik-external

networks:
  traefik-external:
    external: true

