version: '2'
services:
  website:
    build: 
      context: .
      dockerfile: apps/website/Dockerfile
    labels:
      - 'traefik.http.routers.prompto-website.rule=Host(`promp.to`)'
      - 'traefik.http.routers.prompto-website.tls.certresolver=le'
      - 'traefik.http.routers.prompto-website.entrypoints=websecure'
      - 'traefik.docker.network=traefik-external'
    networks:
      - traefik-external

  editor:
    build: 
      context: .
      dockerfile: apps/editor/Dockerfile
    labels:
      - 'traefik.http.routers.prompto-editor.rule=Host(`editor.promp.to`)'
      - 'traefik.http.routers.prompto-editor.tls.certresolver=le'
      - 'traefik.http.routers.prompto-editor.entrypoints=websecure'
      - 'traefik.docker.network=traefik-external'
    networks:
      - traefik-external

  api:
    build: 
      context: .
      dockerfile: apps/api/Dockerfile
    labels:
      - 'traefik.http.routers.prompto-api.rule=Host(`api.promp.to`)'
      - 'traefik.http.routers.prompto-api.tls.certresolver=le'
      - 'traefik.http.routers.prompto-api.entrypoints=websecure'
      - 'traefik.docker.network=traefik-external'
    networks:
      - traefik-external

  postgres:
    image: postgres:15.1
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
    networks:
      - internal

networks:
  traefik-external:
    external: true
  internal:
    external: false

volumes:
  db-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/mnt/volume_lipsumar_io_main/prompto-postgres'
