version: '2'
services:
  website:
    build: 
      context: .
      dockerfile: apps/website/Dockerfile
    ports:
      - "3000:3000"
    
  editor:
    build: 
      context: .
      dockerfile: apps/editor/Dockerfile
    ports:
      - "80:80"    

  postgres:
    image: postgres:15.1
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=password

volumes:
  db-data:
    driver: local
